version: '3.9'

services:

  # api:
  #   container_name: api
  #   build: ./api
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./api:/usr/src/app   
  #   env_file:
  #     - .env

  # worker:
  #   build: .
  #   command: celery --app worker.celery worker --loglevel=info --concurrency=4 -n worker1@%h
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #     - ../.env
  #   depends_on:
  #     - api
  #     - redis

  redis:
    image: redis:7-alpine  
    
  app:
    container_name: app
    build: ./app
    ports:
      - 3000:3000